services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./screenshots:/app/screenshots
      - ./downloads:/app/downloads
      - ./session:/app/session
    restart: "no"
